Principal Component Analysis

In [1]:
import numpy as np
import sklearn.decomposition as skd
import pandas as pd
import os


In [15]:
s12 = -0.8 #correlation coefficient
Sigma = np.matrix([[1, s12, 0.2],\
                   [s12, 1, 0.3],\
                   [0.2, 0.3, 1]])
#create 1000 numbers with multivariate normal distribution, the first two values are highly correlated
X = np.random.multivariate_normal(np.zeros(3), Sigma, 1000) 
print(X[:10,:])

[[-0.3675574  -0.77137188 -1.2368278 ]
 [ 0.21819535 -0.15321238 -0.32674834]
 [-1.33418811  1.02628988 -1.21273909]
 [-0.17766304 -0.18517882  0.35902833]
 [-0.64949722  0.69099674  0.18163593]
 [ 0.49799529  0.43035748  1.83256898]
 [ 1.90580382 -1.63361222 -0.21553176]
 [-0.86255049  0.65721304  0.54345837]
 [ 0.80490112 -1.86321616 -1.21653999]
 [ 1.94918332 -2.4003458  -1.31907964]]


In [16]:
# do it by eigenvalue decomposition
XX = np.matmul(X.T, X)
val, vect = np.linalg.eig(XX)
print (val)
print (vect)
# eigenvalues && eigenvectors
#smaller correlation coefficient will give similar eigenvalues == no more really important component any more

[   67.72156208  1892.42033058  1041.85191488]
[[ 0.65513944  0.66645634  0.35584865]
 [ 0.67025014 -0.73005993  0.13333131]
 [-0.34865034 -0.15115701  0.92498351]]


In [17]:
pca = skd.PCA(3)
pca.fit(X)
print ("components") #almost exactly the same as above
print (pca.components_)
print ("explained variance")
print (pca.explained_variance_)
print ("explained variance ratio")
print (pca.explained_variance_ratio_)


components
[[ 0.66669444 -0.72991696 -0.15079707]
 [ 0.35547     0.13356053  0.92509603]
 [-0.65510275 -0.67036021  0.34850765]]
explained variance
[ 1.8917627   1.04164221  0.06764076]
explained variance ratio
[ 0.63036785  0.34709309  0.02253906]


In [7]:
sie = pd.read_csv(os.path.join(os.environ["HOME"], "tyyq", "infx574", "data", "N_extent_v2.1.csv.gz"))
sie = sie.rename(columns=lambda x: x.strip())
sie.set_value(sie["extent"] < 0, "extent", np.nan)
sie.set_value(sie["area"] < 0, "area", np.nan)
data = pd.DataFrame(np.ones(sum(sie["mo"] == 3)), columns=["const"])
data = data.assign(jan = sie["extent"][sie["mo"] == 1].values)
data = data.assign(feb = sie["extent"][sie["mo"] == 2].values)
data = data.assign(mar = sie["extent"][sie["mo"] == 3].values)
data = data.assign(apr = sie["extent"][sie["mo"] == 4].values)
data = data.assign(may = sie["extent"][sie["mo"] == 5].values)
data = data.assign(jun = sie["extent"][sie["mo"] == 6].values)
data = data.assign(jul = sie["extent"][sie["mo"] == 7].values)
data = data.assign(aug = sie["extent"][sie["mo"] == 8].values)
data = data.assign(sep = sie["extent"][sie["mo"] == 9].values)
data = data.assign(okt = sie["extent"][sie["mo"] == 10].values)
# data = data[["extent", "mo", "year"]]
# data = data.set_index("mo")
# data = data.assign(nov = sie["extent"][sie["mo"] == 11].values)
# data = data.assign(dec = sie["extent"][sie["mo"] == 12].values)
data = data.assign(year = sie["year"][sie["mo"] == 1].values)
print(data.head(3))


FileNotFoundError: [Errno 2] No such file or directory: '/Users/Esther/tyyq/infx574/data/N_extent_v2.1.csv.gz'