Name: Shuyang Wu

Date: 1/11/2017

Section: C
# Linear algebra

This is a voluntary problem set that helps you to learn linear algebra (and the related numpy commands.)  Consult Greene "Econometric Analysis" Appendix A when solving these problems.

If handed in (and solved correctly ;-), it gives you 5 credits.


In [13]:
import numpy as np
from numpy.linalg import matrix_rank
from numpy.linalg import inv
from numpy.linalg import eig
from numpy.linalg import cond
from cmath import sqrt

## 1 Matrix multiplication
* create the following matrices:
a = [ 1 2 3 4], b = [5 6 7 8 ]'
(note: b includes the transposition sign)
* compute the following matrix products $a \cdot b$ and $a' \cdot b'$

In [9]:
a = np.array([[1,2,3,4]])
b = np.array([[5],[6],[7],[8]])
a_prime = a.transpose()
b_prime = b.transpose()
print(a, "\n", b,"\n",a_prime,"\n",b_prime)
print(np.dot(a,b))
print(np.dot(a_prime, b_prime))

[[1 2 3 4]] 
 [[5]
 [6]
 [7]
 [8]] 
 [[1]
 [2]
 [3]
 [4]] 
 [[5 6 7 8]]
[[70]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


## 2 Linear (in)dependence
Consider three vectors:
a = [1 2 3 4],
b = [5 6 7 8] and
c = [9 10 11 12]

* are these vectors linearly independent?  Calculate the rank, a related determinant, and show how they are related/unrelated

They are related. The matrix they formed is not full rank and have a determinant equals to zero.

In [5]:
a = np.array([[1,2,3,4]])
a = a.transpose()
b = np.array([[5,6,7,8]])
b = b.transpose()
c = np.array([[9,10,11,12]])
c = c.transpose()
d = np.concatenate((a, b, c), axis=1)
print(d)
print(matrix_rank(d)) #rank = 2, vectors are not linearly independent
e = d.transpose()
f = np.dot(e, d)
print(f)
w, v = eig(f)
print(w) #Non-zero characteristic roots in d'd
print(matrix_rank(f))  #rank = 2, vectors are not linearly independent
print(np.linalg.det(f))  #can be round to 0 
round(np.linalg.det(f),6) #they are related

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
2
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
[  6.47032607e+02   2.96739296e+00   2.51477877e-14]
2
5.68434188608e-13


0.0

## 3 Find the inverses of the following matrices:


A = [ <br/>
    1 2 3 4 <br/>
5 6 7 8 <br/>
-1 10 11 12 <br/>
13 14 15 17 ],

B = [ <br/>
    1 0 0 <br/>
     0 4 0 <br/>
     0 0 16]

and

C = [ <br/>
    1 2 3 4 <br/>
      5 6 7 8 <br/>
      9 10 11 12 <br/>
      13 14 15 17 ]

* Check the results by left- and right multiplication of the inverse.  Explain.

Only Matrix B is a square matrix and invertible. A and C are singular matrices.

In [27]:
A = [[1, 2, 3, 4], [5, 6, 7, 8], [-1, 10, 11, 12], [13, 14, 15, 17]]
B = [[1, 0, 0], [0, 4, 0], [0, 0, 16]]
C = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12], [13, 14, 15, 17]]
invA = inv(A)
invB = inv(B)
invC = inv(C)
print("A: ","\n", invA, "\n","B: ","\n", invB,"\n", "C: ","\n", invC)
print(np.dot(A,invA) == np.dot(invA, A))
print(np.dot(B,invB) == np.dot(invB, B))
print(np.dot(C,invC) == np.dot(invC, C))
#Only Matrix B is a square matrix and invertible. A and C are singular matrices.

A:  
 [[ -1.00000000e-01   2.00000000e-01  -1.00000000e-01   1.70803542e-16]
 [  4.50000000e-01  -2.65000000e+00   2.00000000e-01   1.00000000e+00]
 [ -2.60000000e+00   5.70000000e+00  -1.00000000e-01  -2.00000000e+00]
 [  2.00000000e+00  -3.00000000e+00  -7.40148683e-17   1.00000000e+00]] 
 B:  
 [[ 1.      0.      0.    ]
 [ 0.      0.25    0.    ]
 [ 0.      0.      0.0625]] 
 C:  
 [[ -1.54070514e+15   3.08141027e+15  -1.54070514e+15   1.87000000e+00]
 [  3.08141027e+15  -6.16282054e+15   3.08141027e+15  -2.74000000e+00]
 [ -1.54070514e+15   3.08141027e+15  -1.54070514e+15  -1.30000000e-01]
 [  1.15789474e+00  -1.31578947e+00  -8.42105263e-01   1.00000000e+00]]


TypeError: only length-1 arrays can be converted to Python scalars

## 4 Characteristic roots
* Find the roots (eigenvalues) of the matrices A, B, C above.
* Calculate the condition numbers of these matrices in two ways: the default numpy way, and in this way as it is explained in Greene (2003, page 829)
* Explain the results

The condition numbers from two ways of calculation are not the same, first of all, the minimun roots of A and C are negative numbers when using Greene's way. Also, the default calculation used by python might not have taken the squareroots of the [max/min].

In [22]:
w, v = eig(A)
print("Characteristic roots of A: ", w)
w, v = eig(B)
print("Characteristic roots of B: ", w)
w, v = eig(C)
print("Characteristic roots of C: ", w)

#defualt way
print("Default way for A: ", cond(A))
print("Default way for A: ",cond(B))
print("Default way for A: ",cond(C))

#Greene
a, v = eig(A)
amx = np.amax(a)
amn = min(a)
conda = sqrt(amx/amn)
print("Greene's way for A: ", conda)
b, v = eig(B)
bmx = np.amax(b)
bmn = min(b)
condb = sqrt(bmx/bmn)
print("Greene's way for B: ", condb)
c, v = eig(C)
cmx = np.amax(c)
cmn = min(c)
condc = sqrt(cmx/cmn)
print("Greene's way for C: ", condc)

Characteristic roots of A:  [ 35.83449756   1.34371891  -1.6853005   -0.49291597]
Characteristic roots of B:  [  1.   4.  16.]
Characteristic roots of C:  [  3.66727818e+01  -2.00000000e+00  -2.08470091e-15   3.27218155e-01]
Default way for A:  299.050204082
Default way for A:  16.0
Default way for A:  7.60469682786e+16
Greene's way for A:  4.6111790371235095j
Greene's way for B:  (4+0j)
Greene's way for C:  4.282101227515895j
